I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1055, in script
    menu:
ScriptError: could not find label 'afternightshade1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Saknoops\Desktop\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\Saknoops\Desktop\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Users\Saknoops\Desktop\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "C:\Users\Saknoops\Desktop\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "game/script.rpy", line 1055, in script
    menu:
  File "C:\Users\Saknoops\Desktop\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'afternightshade1'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Vanitas 1.0
Mon Aug 24 17:49:48 2020
